# Generated by Django 4.1.2 on 2022-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('package_dis', models.CharField(max_length=50)),
                ('package_image', models.ImageField(default='', upload_to='traveling/image')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
