# Generated by Django 4.1.2 on 2022-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations_name', models.CharField(max_length=50)),
                ('destinations_dis', models.CharField(max_length=50)),
                ('destinations_image', models.ImageField(default='', upload_to='traveling/image')),
                ('destinations_date', models.DateField()),
            ],
        ),
    ]
