# Generated by Django 4.1.2 on 2022-11-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0002_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('arrivals', models.CharField(max_length=50)),
                ('leaving', models.CharField(max_length=50)),
                ('guests', models.CharField(max_length=50)),
            ],
        ),
    ]
